server:
  port: 8081

spring:
  application:
    name: configserver

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Aravind100-dot/microservices-demo.git
          clone-on-start: true
          default-label: main
          search-paths: /configserver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Replace with your Eureka server URL
    register-with-eureka: true
    fetch-registry: true
