spring:
  config:
    import: "configserver:http://localhost:8081"  # Config Server URL
  application:
    name: orderservice
  profiles:
    active: dev

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
    register-with-eureka: true
    fetch-registry: true
